# Generated by Django 3.2.6 on 2021-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='comany_email',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='comany_name',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company_email',
            field=models.EmailField(default='a@a.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(default='company', max_length=100),
            preserve_default=False,
        ),
    ]
